name: Print uname -a

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  print-uname:
    runs-on: self-hosted
    strategy:
      matrix:
        runner_type: ['c3-large-arm64-mahe']

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Print uname -a
        run: |
          uname -a
